trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  resource_group_name: "tfstate"
  location : "eastus"

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@0
  displayName: 'Install Terraform'
  inputs:
    terraformVersion: $(terraformVersion)

- script: |
    terraform init
    terraform validate
  displayName: 'Terraform Init and Validate'

- script: terraform plan -out=tfplan -var="resource_group_name=$(resourceGroupName)" -var="location=$(location)"
  displayName: 'Terraform Plan'

- script: terraform apply -input=false tfplan
  displayName: 'Terraform Apply'
  condition: succeeded()